name = "PolynomialBasis"
uuid = "776a168a-1973-4f1d-bada-3c06b642fffd"
authors = ["Arjun Narayanan"]
version = "0.1.0"

[deps]
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticPolynomials = "62e018b1-6e46-5407-a5a7-97d4fbcae734"

[compat]
DynamicPolynomials = "0.3"
julia = "1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
